name: Experiment
on: 
  schedule:
  # - cron: '*/5 * * * *'
  - cron: '40 15 * * 3'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: List files
      run: ls
